#!/usr/bin/env python3
"""Add more irregular verbs to the conjugation map."""

# Read the current lib.rs
with open('src/lib.rs', 'r') as f:
    content = f.read()

# Define additional verbs to add
additional_verbs = [
    ("begin", "began"),
    ("drink", "drank"),
    ("ring", "rang"),
    ("sing", "sang"),
    ("swim", "swam"),
    ("write", "wrote"),
    ("ride", "rode"),
    ("drive", "drove"),
    ("fall", "fell"),
    ("feed", "fed"),
    ("feel", "felt"),
    ("fight", "fought"),
    ("find", "found"),
    ("fit", "fit"),
    ("fly", "flew"),
    ("forget", "forgot"),
    ("forgive", "forgave"),
    ("freeze", "froze"),
    ("get", "got"),
    ("give", "gave"),
    ("go", "went"),
    ("grow", "grew"),
    ("hang", "hung"),
    ("have", "had"),
    ("hear", "heard"),
    ("hide", "hid"),
    ("hit", "hit"),
    ("hold", "held"),
    ("hurt", "hurt"),
    ("keep", "kept"),
    ("kneel", "knelt"),
    ("know", "knew"),
    ("lay", "laid"),
    ("lead", "led"),
    ("lean", "leaned"),  # or leant
    ("learn", "learned"),  # or learnt
    ("leave", "left"),
    ("lend", "lent"),
    ("let", "let"),
    ("lie", "lay"),
    ("light", "lit"),
    ("lose", "lost"),
    ("make", "made"),
    ("mean", "meant"),
    ("meet", "met"),
    ("pay", "paid"),
    ("put", "put"),
    ("quit", "quit"),
    ("read", "read"),
    ("ride", "rode"),
    ("ring", "rang"),
    ("rise", "rose"),
    ("run", "ran"),
    ("say", "said"),
    ("see", "saw"),
    ("seek", "sought"),
    ("sell", "sold"),
    ("send", "sent"),
    ("set", "set"),
    ("sew", "sewed"),
    ("shake", "shook"),
    ("shine", "shone"),
    ("shoot", "shot"),
    ("show", "showed"),
    ("shrink", "shrank"),
    ("shut", "shut"),
    ("sing", "sang"),
    ("sink", "sank"),
    ("sit", "sat"),
    ("sleep", "slept"),
    ("slide", "slid"),
    ("speak", "spoke"),
    ("spend", "spent"),
    ("spill", "spilled"),
    ("split", "split"),
    ("spread", "spread"),
    ("spring", "sprang"),
    ("stand", "stood"),
    ("steal", "stole"),
    ("stick", "stuck"),
    ("sting", "stung"),
    ("stink", "stank"),
    ("strike", "struck"),
    ("swear", "swore"),
    ("sweep", "swept"),
    ("swell", "swelled"),
    ("swim", "swam"),
    ("swing", "swung"),
    ("take", "took"),
    ("teach", "taught"),
    ("tear", "tore"),
    ("tell", "told"),
    ("think", "thought"),
    ("throw", "threw"),
    ("understand", "understood"),
    ("wake", "woke"),
    ("wear", "wore"),
    ("weave", "wove"),
    ("weep", "wept"),
    ("win", "won"),
    ("wind", "wound"),
    ("wring", "wrung"),
    ("write", "wrote"),
    ("zinc", "zincked"),
]

# Insert these into the verb_conjugations map
# Find the existing map and append new entries before the closing bracket
import re

# Find the line with .collect(); and insert new entries before it
pattern = r"(            \"joined\",\n        ]\n        \.iter\(\)\n        \.cloned\(\)\n        \.collect\(\);)"
replacement = f"""            "joined",
        ]
        .iter()
        .cloned()
        .collect();"""

# Actually, we need to insert the new verbs before the closing bracket
# Let's find the line with "joined", and insert new entries after it but before the closing bracket
pattern = r"(            \"joined\",\n        \])"
replacement = f"""            "joined",
            "began", "began",  // begin → began (note: participle is begun)
            "blew", "blew",
            "broke", "broke",
            "chose", "chose",
            "came", "came",
            "crept", "crept",
            "drew", "drew",
            "drove", "drove",
            "ate", "ate",
            "fell", "fell",
            "flew", "flew",
            "forgot", "forgot",
            "froze", "froze",
            "grew", "grew",
            "knew", "knew",
            "leapt", "leapt",
            "lost", "lost",
            "met", "met",
            "paid", "paid",
            "rang", "rang",
            "rose", "rose",
            "sang", "sang",
            "sank", "sank",
            "spoke", "spoke",
            "stank", "stank",
            "stole", "stole",
            "strode", "strode",
            "swelled", "swelled",
            "swam", "swam",
            "took", "took",
            "tore", "tore",
            "wore", "wore",
            "wove", "wove",
            "wrote", "wrote",
            // More irregular verbs
            "bit", "bit",
            "bled", "bled",
            "bred", "bred",
            "bought", "bought",
            "caught", "caught",
            "cost", "cost",
            "cut", "cut",
            "dealt", "dealt",
            "dug", "dug",
            "dreamed", "dreamed",
            "drank", "drank",
            "fed", "fed",
            "felt", "felt",
            "fought", "fought",
            "found", "found",
            "fled", "fled",
            "forbade", "forbade",
            "forgave", "forgave",
            "forsook", "forsook",
            "got", "got",
            "ground", "ground",
            "hung", "hung",
            "had", "had",
            "heard", "heard",
            "hid", "hid",
            "hit", "hit",
            "kept", "kept",
            "laid", "laid",
            "led", "led",
            "left", "left",
            "lent", "lent",
            "lay", "lay",
            "lit", "lit",
            "lost", "lost",
            "made", "made",
            "meant", "meant",
            "paid", "paid",
            "pled", "pled",
            "put", "put",
            "quit", "quit",
            "read", "read",
            "rode", "rode",
            "rose", "rose",
            "ran", "ran",
            "said", "said",
            "sold", "sold",
            "sent", "sent",
            "set", "set",
            "sewed", "sewed",
            "shook", "shook",
            "shrank", "shrank",
            "shot", "shot",
            "showed", "showed",
            "slid", "slid",
            "split", "split",
            "spoke", "spoke",
            "spent", "spent",
            "spun", "spun",
            "stank", "stank",
            "stole", "stole",
            "stuck", "stuck",
            "stung", "stung",
            "struck", "struck",
            "sought", "sought",
            "swore", "swore",
            "swept", "swept",
            "swelled", "swelled",
            "swam", "swam",
            "swung", "swung",
            "taught", "taught",
            "tore", "tore",
            "told", "told",
            "thought", "thought",
            "threw", "threw",
            "understood", "understood",
            "woke", "woke",
            "wore", "wore",
            "wove", "wove",
            "wept", "wept",
            "won", "won",
            "wound", "wound",
            "wrote", "wrote",
        ]
        .iter()
        .cloned()
        .collect();"""

content = re.sub(pattern, replacement, content)

# Write back
with open('src/lib.rs', 'w') as f:
    f.write(content)

print("Added more irregular verbs to the conjugation map.")