[package]
name = "rust-cave-001"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_cave_001"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
lz4 = "1.0"
regex = "1.10.0"
bincode = "1.0"
serde = "1.0.228"
serde_json = "1.0.149"

[build-dependencies]
pyo3-macros = "0.24.2"