//! Verb conjugation maps for Caveman Compression.
//!
//! Two maps:
//! - `PAST_PARTICIPLE_TO_SIMPLE_PAST`: Used by `transform_active_voice` to convert
//!   passive-voice patterns ("was thrown") into active voice ("threw").
//! - `SIMPLE_PAST_TO_PRESENT`: Used by `normalize_present_tense` to convert past-tense
//!   verbs ("threw") into present base form ("throw").
//!
//! Each map focuses on irregular forms that simple rule-based stripping ("ed" -> "")
//! would handle incorrectly or not at all. Regular -ed verbs are handled by the fallback
//! in the calling functions.

use std::collections::HashMap;
use std::sync::OnceLock;

/// Cached past-participle → simple-past map (avoids rebuilding 192-entry HashMap per sentence).
static PP_CACHE: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();

/// Cached simple-past → present-base map (avoids rebuilding 220-entry HashMap per sentence).
static SP_CACHE: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();

/// Map of past participles to simple past forms for passive-to-active transformation.
///
/// Covers:
/// - Irregular verbs where past participle != simple past (e.g., "thrown" → "threw")
/// - No-change verbs where both forms are identical but don't end in "ed" (e.g., "beat" → "beat")
/// - Common -ed verbs where past participle == simple past (for lookup speed, avoiding regex fallback)
///
/// Total: 192 entries
pub static PAST_PARTICIPLE_TO_SIMPLE_PAST: &[(&str, &str)] = &[
    // ── Preserved from v0.2.1 (94 entries) ──────────────────────────────────
    ("thrown", "threw"),
    ("eaten", "ate"),
    ("written", "wrote"),
    ("seen", "saw"),
    ("done", "did"),
    ("given", "gave"),
    ("taken", "took"),
    ("made", "made"),
    ("found", "found"),
    ("told", "told"),
    ("called", "called"),
    ("used", "used"),
    ("asked", "asked"),
    ("wanted", "wanted"),
    ("needed", "needed"),
    ("looked", "looked"),
    ("worked", "worked"),
    ("played", "played"),
    ("moved", "moved"),
    ("lived", "lived"),
    ("believed", "believed"),
    ("changed", "changed"),
    ("showed", "showed"),
    ("watched", "watched"),
    ("followed", "followed"),
    ("stopped", "stopped"),
    ("created", "created"),
    ("brought", "brought"),
    ("heard", "heard"),
    ("held", "held"),
    ("sent", "sent"),
    ("built", "built"),
    ("understood", "understood"),
    ("drawn", "drew"),
    ("grown", "grew"),
    ("flown", "flew"),
    ("broken", "broke"),
    ("sung", "sang"),
    ("drunk", "drank"),
    ("sunk", "sank"),
    ("spun", "spun"),
    ("run", "ran"),
    ("read", "read"),
    ("cut", "cut"),
    ("put", "put"),
    ("set", "set"),
    ("shut", "shut"),
    ("cost", "cost"),
    ("hurt", "hurt"),
    ("let", "let"),
    ("regretted", "regretted"),
    ("begun", "began"),
    ("chosen", "chose"),
    ("come", "came"),
    ("driven", "drove"),
    ("fallen", "fell"),
    ("fed", "fed"),
    ("felt", "felt"),
    ("fought", "fought"),
    ("forgotten", "forgot"),
    ("forgiven", "forgave"),
    ("frozen", "froze"),
    ("gotten", "got"),
    ("gone", "went"),
    ("had", "had"),
    ("hidden", "hid"),
    ("hit", "hit"),
    ("kept", "kept"),
    ("known", "knew"),
    ("led", "led"),
    ("learned", "learned"),
    ("left", "left"),
    ("lent", "lent"),
    ("lain", "lay"),
    ("lost", "lost"),
    ("meant", "meant"),
    ("met", "met"),
    ("paid", "paid"),
    ("ridden", "rode"),
    ("rung", "rang"),
    ("said", "said"),
    ("sold", "sold"),
    ("shown", "showed"),
    ("sat", "sat"),
    ("slept", "slept"),
    ("spoken", "spoke"),
    ("spent", "spent"),
    ("stood", "stood"),
    ("swum", "swam"),
    ("taught", "taught"),
    ("thought", "thought"),
    ("worn", "wore"),
    ("won", "won"),
    // ── NEW v0.3.0: No-change verbs (pp == sp, not -ed ending) ──────────────
    ("beat", "beat"),
    ("bet", "bet"),
    ("bid", "bid"),
    ("burst", "burst"),
    ("cast", "cast"),
    ("forecast", "forecast"),
    ("quit", "quit"),
    ("shed", "shed"),
    ("slit", "slit"),
    ("split", "split"),
    ("spread", "spread"),
    ("thrust", "thrust"),
    ("upset", "upset"),
    ("wed", "wed"),
    ("wet", "wet"),
    // ── NEW v0.3.0: Major irregulars (pp != sp) ────────────────────────────
    ("arisen", "arose"),
    ("awoken", "awoke"),
    ("bent", "bent"),
    ("bitten", "bit"),
    ("bled", "bled"),
    ("blown", "blew"),
    ("bound", "bound"),
    ("bred", "bred"),
    ("caught", "caught"),
    ("clung", "clung"),
    ("crept", "crept"),
    ("dealt", "dealt"),
    ("dug", "dug"),
    ("dived", "dove"),
    ("dreamt", "dreamt"),
    ("dwelt", "dwelt"),
    ("fled", "fled"),
    ("flung", "flung"),
    ("forbidden", "forbade"),
    ("ground", "ground"),
    ("hung", "hung"),
    ("knelt", "knelt"),
    ("knitted", "knitted"),
    ("laid", "laid"),
    ("leant", "leant"),
    ("leapt", "leapt"),
    ("lit", "lit"),
    ("misled", "misled"),
    ("mistaken", "mistook"),
    ("overcome", "overcame"),
    ("overthrown", "overthrew"),
    ("partaken", "partook"),
    ("rebuilt", "rebuilt"),
    ("redone", "redid"),
    ("remade", "remade"),
    ("repaid", "repaid"),
    ("rewound", "rewound"),
    ("shaken", "shook"),
    ("shone", "shone"),
    ("shot", "shot"),
    ("shrunk", "shrunk"),
    ("slain", "slew"),
    ("slid", "slid"),
    ("slung", "slung"),
    ("slunk", "slunk"),
    ("smelt", "smelt"),
    ("snuck", "snuck"),
    ("sown", "sowed"),
    ("sped", "sped"),
    ("spelt", "spelt"),
    ("spilt", "spilt"),
    ("spat", "spat"),
    ("spoilt", "spoilt"),
    ("sprung", "sprang"),
    ("stolen", "stole"),
    ("stuck", "stuck"),
    ("stung", "stung"),
    ("stunk", "stank"),
    ("stridden", "strode"),
    ("struck", "struck"),
    ("strung", "strung"),
    ("striven", "strove"),
    ("sworn", "swore"),
    ("swept", "swept"),
    ("swollen", "swelled"),
    ("swung", "swung"),
    ("torn", "tore"),
    ("trodden", "trod"),
    ("woken", "woke"),
    ("woven", "wove"),
    ("wept", "wept"),
    ("wound", "wound"),
    ("withdrawn", "withdrew"),
    ("withheld", "withheld"),
    ("withstood", "withstood"),
    ("wrung", "wrung"),
    // ── NEW v0.3.0: -ed ending common same-form verbs ──────────────────────
    ("added", "added"),
    ("allowed", "allowed"),
    ("appeared", "appeared"),
    ("applied", "applied"),
    ("arrived", "arrived"),
    ("avoided", "avoided"),
    ("based", "based"),
    ("carried", "carried"),
    ("caused", "caused"),
    ("checked", "checked"),
    ("claimed", "claimed"),
    ("closed", "closed"),
    ("collected", "collected"),
    ("completed", "completed"),
    ("connected", "connected"),
    ("considered", "considered"),
    ("contained", "contained"),
    ("continued", "continued"),
    ("covered", "covered"),
    ("decided", "decided"),
    ("delivered", "delivered"),
    ("described", "described"),
    ("designed", "designed"),
    ("developed", "developed"),
    ("discovered", "discovered"),
    ("discussed", "discussed"),
    ("enabled", "enabled"),
    ("enjoyed", "enjoyed"),
    ("entered", "entered"),
    ("established", "established"),
    ("expected", "expected"),
    ("explained", "explained"),
    ("expressed", "expressed"),
    ("extended", "extended"),
    ("failed", "failed"),
    ("finished", "finished"),
    ("fixed", "fixed"),
    ("forced", "forced"),
    ("formed", "formed"),
    ("handled", "handled"),
    ("helped", "helped"),
    ("identified", "identified"),
    ("improved", "improved"),
    ("included", "included"),
    ("increased", "increased"),
    ("indicated", "indicated"),
    ("informed", "informed"),
    ("installed", "installed"),
    ("introduced", "introduced"),
    ("invented", "invented"),
    ("invited", "invited"),
    ("involved", "involved"),
    ("launched", "launched"),
    ("managed", "managed"),
    ("marked", "marked"),
    ("measured", "measured"),
    ("mentioned", "mentioned"),
    ("noticed", "noticed"),
    ("obtained", "obtained"),
    ("offered", "offered"),
    ("opened", "opened"),
    ("ordered", "ordered"),
    ("passed", "passed"),
    ("performed", "performed"),
    ("placed", "placed"),
    ("prepared", "prepared"),
    ("presented", "presented"),
    ("prevented", "prevented"),
    ("processed", "processed"),
    ("produced", "produced"),
    ("promised", "promised"),
    ("protected", "protected"),
    ("provided", "provided"),
    ("raised", "raised"),
    ("reached", "reached"),
    ("realized", "realized"),
    ("received", "received"),
    ("recorded", "recorded"),
    ("reduced", "reduced"),
    ("released", "released"),
    ("remembered", "remembered"),
    ("removed", "removed"),
    ("reported", "reported"),
    ("required", "required"),
    ("returned", "returned"),
    ("reviewed", "reviewed"),
    ("saved", "saved"),
    ("selected", "selected"),
    ("separated", "separated"),
    ("served", "served"),
    ("shaped", "shaped"),
    ("shared", "shared"),
    ("simplified", "simplified"),
    ("solved", "solved"),
    ("sorted", "sorted"),
    ("started", "started"),
    ("stated", "stated"),
    ("stored", "stored"),
    ("studied", "studied"),
    ("submitted", "submitted"),
    ("suggested", "suggested"),
    ("supported", "supported"),
    ("supposed", "supposed"),
    ("talked", "talked"),
    ("tested", "tested"),
    ("tracked", "tracked"),
    ("trained", "trained"),
    ("transformed", "transformed"),
    ("treated", "treated"),
    ("turned", "turned"),
    ("updated", "updated"),
    ("validated", "validated"),
    ("verified", "verified"),
    ("viewed", "viewed"),
    ("visited", "visited"),
    ("waited", "waited"),
    ("walked", "walked"),
    ("warned", "warned"),
    ("washed", "washed"),
    ("wished", "wished"),
    ("wondered", "wondered"),
    ("worried", "worried"),
];

/// Map of simple past → present base form for present-tense normalization.
///
/// Covers irregular simple-past forms plus common regular -ed verbs for fast lookup,
/// avoiding the regex fallback for high-frequency words.
///
/// Total: 220 entries
pub static SIMPLE_PAST_TO_PRESENT: &[(&str, &str)] = &[
    // ── Preserved from v0.2.1 (147 entries) ─────────────────────────────────
    ("threw", "throw"),
    ("ate", "eat"),
    ("wrote", "write"),
    ("saw", "see"),
    ("did", "do"),
    ("gave", "give"),
    ("took", "take"),
    ("made", "make"),
    ("found", "find"),
    ("told", "tell"),
    ("called", "call"),
    ("used", "use"),
    ("asked", "ask"),
    ("wanted", "want"),
    ("needed", "need"),
    ("looked", "look"),
    ("worked", "work"),
    ("played", "play"),
    ("moved", "move"),
    ("lived", "live"),
    ("believed", "believe"),
    ("happened", "happen"),
    ("changed", "change"),
    ("showed", "show"),
    ("watched", "watch"),
    ("followed", "follow"),
    ("stopped", "stop"),
    ("brought", "bring"),
    ("heard", "hear"),
    ("held", "hold"),
    ("sent", "send"),
    ("built", "build"),
    ("understood", "understand"),
    ("drew", "draw"),
    ("grew", "grow"),
    ("flew", "fly"),
    ("broke", "break"),
    ("sang", "sing"),
    ("drank", "drink"),
    ("sank", "sink"),
    ("spun", "spin"),
    ("ran", "run"),
    ("began", "begin"),
    ("chose", "choose"),
    ("came", "come"),
    ("drove", "drive"),
    ("fell", "fall"),
    ("fed", "feed"),
    ("felt", "feel"),
    ("fought", "fight"),
    ("forgot", "forget"),
    ("forgave", "forgive"),
    ("froze", "freeze"),
    ("got", "get"),
    ("went", "go"),
    ("hid", "hide"),
    ("kept", "keep"),
    ("knew", "know"),
    ("led", "lead"),
    ("learned", "learn"),
    ("left", "leave"),
    ("lent", "lend"),
    ("lay", "lie"),
    ("lost", "lose"),
    ("meant", "mean"),
    ("met", "meet"),
    ("paid", "pay"),
    ("rode", "ride"),
    ("rang", "ring"),
    ("said", "say"),
    ("sold", "sell"),
    ("sat", "sit"),
    ("slept", "sleep"),
    ("spoke", "speak"),
    ("spent", "spend"),
    ("stood", "stand"),
    ("swam", "swim"),
    ("taught", "teach"),
    ("thought", "think"),
    ("wore", "wear"),
    ("won", "win"),
    ("regretted", "regret"),
    ("forgotten", "forget"),
    ("forgiven", "forgive"),
    ("frozen", "freeze"),
    ("gotten", "get"),
    ("hidden", "hide"),
    ("ridden", "ride"),
    ("rung", "ring"),
    ("shown", "show"),
    ("spoken", "speak"),
    ("swum", "swim"),
    ("worn", "wear"),
    ("written", "write"),
    ("driven", "drive"),
    ("eaten", "eat"),
    ("fallen", "fall"),
    ("flown", "fly"),
    ("given", "give"),
    ("grown", "grow"),
    ("known", "know"),
    ("lain", "lie"),
    ("risen", "rise"),
    ("shaken", "shake"),
    ("shrunk", "shrink"),
    ("sung", "sing"),
    ("sunk", "sink"),
    ("stolen", "steal"),
    ("thrown", "throw"),
    ("taken", "take"),
    ("torn", "tear"),
    ("woken", "wake"),
    ("broken", "break"),
    ("chosen", "choose"),
    ("drawn", "draw"),
    ("drunk", "drink"),
    // E-drop regular verbs (base ends in "e", past adds "d")
    ("agreed", "agree"),
    ("planned", "plan"),
    ("merged", "merge"),
    ("cached", "cache"),
    ("parsed", "parse"),
    ("loaded", "load"),
    ("saved", "save"),
    ("proved", "prove"),
    ("loved", "love"),
    ("liked", "like"),
    ("hoped", "hope"),
    ("cared", "care"),
    ("shared", "share"),
    ("stared", "stare"),
    ("dated", "date"),
    ("noted", "note"),
    ("quoted", "quote"),
    ("wasted", "waste"),
    ("tasted", "taste"),
    ("hated", "hate"),
    ("created", "create"),
    // Same-form verbs (past == present == base)
    ("cost", "cost"),
    ("cut", "cut"),
    ("hit", "hit"),
    ("hurt", "hurt"),
    ("let", "let"),
    ("put", "put"),
    ("read", "read"),
    ("set", "set"),
    ("shut", "shut"),
    ("spread", "spread"),
    // ── NEW v0.3.0: Fixed missing same-form no-change verbs ────────────────
    ("beat", "beat"),
    ("bet", "bet"),
    ("bid", "bid"),
    ("burst", "burst"),
    ("cast", "cast"),
    ("forecast", "forecast"),
    ("quit", "quit"),
    ("shed", "shed"),
    ("slit", "slit"),
    ("split", "split"),
    ("thrust", "thrust"),
    ("upset", "upset"),
    ("wed", "wed"),
    ("wet", "wet"),
    // ── NEW v0.3.0: Irregular simple-past forms ─────────────────────────────
    ("arose", "arise"),
    ("awoke", "awake"),
    ("bent", "bend"),
    ("bit", "bite"),
    ("bled", "bleed"),
    ("blew", "blow"),
    ("bound", "bind"),
    ("bred", "breed"),
    ("caught", "catch"),
    ("clung", "cling"),
    ("crept", "creep"),
    ("dealt", "deal"),
    ("dove", "dive"),
    ("dreamt", "dream"),
    ("dwelt", "dwell"),
    ("fled", "flee"),
    ("flung", "fling"),
    ("forbade", "forbid"),
    ("ground", "grind"),
    ("hung", "hang"),
    ("knelt", "kneel"),
    ("knitted", "knit"),
    ("laid", "lay"),
    ("leant", "lean"),
    ("leapt", "leap"),
    ("lit", "light"),
    ("misled", "mislead"),
    ("mistook", "mistake"),
    ("overcame", "overcome"),
    ("overthrew", "overthrow"),
    ("partook", "partake"),
    ("rebuilt", "rebuild"),
    ("redid", "redo"),
    ("remade", "remake"),
    ("repaid", "repay"),
    ("rewound", "rewind"),
    ("shook", "shake"),
    ("shone", "shine"),
    ("shot", "shoot"),
    ("slew", "slay"),
    ("slid", "slide"),
    ("slung", "sling"),
    ("slunk", "slink"),
    ("smelt", "smell"),
    ("snuck", "sneak"),
    ("sowed", "sow"),
    ("sped", "speed"),
    ("spelt", "spell"),
    ("spilt", "spill"),
    ("spat", "spit"),
    ("spoilt", "spoil"),
    ("sprang", "spring"),
    ("stole", "steal"),
    ("stuck", "stick"),
    ("stung", "sting"),
    ("stank", "stink"),
    ("strode", "stride"),
    ("struck", "strike"),
    ("strung", "string"),
    ("strove", "strive"),
    ("swore", "swear"),
    ("swept", "sweep"),
    ("swelled", "swell"),
    ("swung", "swing"),
    ("tore", "tear"),
    ("trod", "tread"),
    ("woke", "wake"),
    ("wove", "weave"),
    ("wept", "weep"),
    ("wound", "wind"),
    ("withdrew", "withdraw"),
    ("withheld", "withhold"),
    ("withstood", "withstand"),
    ("wrung", "wring"),
    // ── NEW v0.3.0: Fixed missing PP→sp simple-past forms ──────────────────
    ("had", "have"),
    ("dug", "dig"),
    // ── NEW v0.3.0: -ed ending common -ed verbs (not in v0.2.1 preserved section)
    ("added", "add"),
    ("allowed", "allow"),
    ("appeared", "appear"),
    ("applied", "apply"),
    ("arrived", "arrive"),
    ("avoided", "avoid"),
    ("based", "base"),
    ("carried", "carry"),
    ("caused", "cause"),
    ("checked", "check"),
    ("claimed", "claim"),
    ("closed", "close"),
    ("collected", "collect"),
    ("completed", "complete"),
    ("connected", "connect"),
    ("considered", "consider"),
    ("contained", "contain"),
    ("continued", "continue"),
    ("covered", "cover"),
    ("decided", "decide"),
    ("delivered", "deliver"),
    ("described", "describe"),
    ("designed", "design"),
    ("developed", "develop"),
    ("discovered", "discover"),
    ("discussed", "discuss"),
    ("enabled", "enable"),
    ("enjoyed", "enjoy"),
    ("entered", "enter"),
    ("established", "establish"),
    ("expected", "expect"),
    ("explained", "explain"),
    ("expressed", "express"),
    ("extended", "extend"),
    ("failed", "fail"),
    ("finished", "finish"),
    ("fixed", "fix"),
    ("forced", "force"),
    ("formed", "form"),
    ("handled", "handle"),
    ("helped", "help"),
    ("identified", "identify"),
    ("improved", "improve"),
    ("included", "include"),
    ("increased", "increase"),
    ("indicated", "indicate"),
    ("informed", "inform"),
    ("installed", "install"),
    ("introduced", "introduce"),
    ("invented", "invent"),
    ("invited", "invite"),
    ("involved", "involve"),
    ("launched", "launch"),
    ("managed", "manage"),
    ("marked", "mark"),
    ("measured", "measure"),
    ("mentioned", "mention"),
    ("noticed", "notice"),
    ("obtained", "obtain"),
    ("offered", "offer"),
    ("opened", "open"),
    ("ordered", "order"),
    ("passed", "pass"),
    ("performed", "perform"),
    ("placed", "place"),
    ("prepared", "prepare"),
    ("presented", "present"),
    ("prevented", "prevent"),
    ("processed", "process"),
    ("produced", "produce"),
    ("promised", "promise"),
    ("protected", "protect"),
    ("provided", "provide"),
    ("raised", "raise"),
    ("reached", "reach"),
    ("realized", "realize"),
    ("received", "receive"),
    ("recorded", "record"),
    ("reduced", "reduce"),
    ("released", "release"),
    ("remembered", "remember"),
    ("removed", "remove"),
    ("reported", "report"),
    ("required", "require"),
    ("returned", "return"),
    ("reviewed", "review"),
    ("selected", "select"),
    ("separated", "separate"),
    ("served", "serve"),
    ("shaped", "shape"),
    ("simplified", "simplify"),
    ("solved", "solve"),
    ("sorted", "sort"),
    ("started", "start"),
    ("stated", "state"),
    ("stored", "store"),
    ("studied", "study"),
    ("submitted", "submit"),
    ("suggested", "suggest"),
    ("supported", "support"),
    ("supposed", "suppose"),
    ("talked", "talk"),
    ("tested", "test"),
    ("tracked", "track"),
    ("trained", "train"),
    ("transformed", "transform"),
    ("treated", "treat"),
    ("turned", "turn"),
    ("updated", "update"),
    ("validated", "validate"),
    ("verified", "verify"),
    ("viewed", "view"),
    ("visited", "visit"),
    ("waited", "wait"),
    ("walked", "walk"),
    ("warned", "warn"),
    ("washed", "wash"),
    ("wished", "wish"),
    ("wondered", "wonder"),
    ("worried", "worry"),
];

/// Returns a cached reference to the past-participle → simple-past map.
pub fn verb_conjugation_map() -> &'static HashMap<&'static str, &'static str> {
    PP_CACHE.get_or_init(|| PAST_PARTICIPLE_TO_SIMPLE_PAST.iter().cloned().collect())
}

/// Returns a cached reference to the simple-past → present-base map.
pub fn present_tense_map() -> &'static HashMap<&'static str, &'static str> {
    SP_CACHE.get_or_init(|| SIMPLE_PAST_TO_PRESENT.iter().cloned().collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_verb_map_no_duplicate_keys() {
        let map = verb_conjugation_map();
        assert_eq!(
            map.len(),
            PAST_PARTICIPLE_TO_SIMPLE_PAST.len(),
            "Duplicate past participle keys detected in PAST_PARTICIPLE_TO_SIMPLE_PAST"
        );
    }

    #[test]
    fn test_present_map_no_duplicate_keys() {
        let map = present_tense_map();
        assert_eq!(
            map.len(),
            SIMPLE_PAST_TO_PRESENT.len(),
            "Duplicate simple-past keys detected in SIMPLE_PAST_TO_PRESENT"
        );
    }

    #[test]
    fn test_verb_map_minimum_count() {
        assert!(
            PAST_PARTICIPLE_TO_SIMPLE_PAST.len() >= 150,
            "PAST_PARTICIPLE_TO_SIMPLE_PAST has {} entries, expected >= 150",
            PAST_PARTICIPLE_TO_SIMPLE_PAST.len()
        );
    }

    #[test]
    fn test_present_map_minimum_count() {
        assert!(
            SIMPLE_PAST_TO_PRESENT.len() >= 200,
            "SIMPLE_PAST_TO_PRESENT has {} entries, expected >= 200",
            SIMPLE_PAST_TO_PRESENT.len()
        );
    }

    #[test]
    fn test_verb_map_symmetry() {
        // Verify key verbs appear in BOTH maps (transform-active -> normalize consistency)
        let past_pp = verb_conjugation_map();
        let past_pres = present_tense_map();

        // For a core set, pp -> sp -> present should round-trip
        // e.g., "thrown" -> "threw" in pp_map, "threw" -> "throw" in present_map
        let tests = [
            ("thrown", "threw", "throw"),
            ("eaten", "ate", "eat"),
            ("written", "wrote", "write"),
            ("broken", "broke", "break"),
            ("flown", "flew", "fly"),
            ("taken", "took", "take"),
            ("driven", "drove", "drive"),
            ("forgotten", "forgot", "forget"),
        ];
        for (pp, sp, pres) in &tests {
            assert_eq!(
                past_pp.get(pp),
                Some(sp),
                "PP map missing '{pp}' or wrong simple-past"
            );
            assert_eq!(
                past_pres.get(sp),
                Some(pres),
                "Present map missing '{sp}' or wrong present"
            );
        }
    }
}
